### ISSUE TITLE
Allow control of lexer used for syntax highlighting

### ISSUE THREAD

**Issue by SeanDS** [jupyter/jupyter-sphinx#180]
I use `jupyter-sphinx` to show examples using Python to execute an application-specific language:

```rst

.. jupyter-execute:

    # Parse a simple model.
    model.parse(
        """
        l l1 P=10
        s s1 l1.p1 m1.p1
        m m1 R=0.995 T=1-&m1.R
        s s2 m1.p2 m2.p1 L=10
        m m2 R=0.9999 T=1-&m2.R
        pd pd1 m2.p1.i
        pd pd2 m2.p2.o
        """
    )
```

This gets rendered like this:

![image](https://user-images.githubusercontent.com/5225190/115681743-184a4400-a355-11eb-851b-4a6dbcd1e008.png)

I've got a pygments syntax highlighter that can handle highlighting our special syntax inside the string, inside Python code. I would like to change the lexer type used by Sphinx for the cell that gets compiled. This would make it render like this:

![image](https://user-images.githubusercontent.com/5225190/115685569-a07e1880-a358-11eb-84f7-b3b0ae273493.png)

Currently the lexer used by `jupyter-sphinx` is hard-coded [here](https://github.com/jupyter/jupyter-sphinx/blob/28468f22ae8fb9d444ee3b11af04542e7427cb3c/jupyter_sphinx/__init__.py#L285). Is it possible to change this on a per-cell basis?

**Comment by akhmerov** [comment]
AFAIR the lexer isn't hardcoded, the line you refer to is just providing the custom ipython lexer to sphinx.

jupyter-sphinx infers the lexer from kernel metadata. Therefore, I think, you need to register a custom ipython kernel (kernels already have a pygments lexer metadata entry) that executes your code, and then also add your lexer to sphinx.

Does that sound like a reasonable approach?

**Comment by philj56** [comment]
Hi @akhmerov, I'm on the same team as @SeanDS. Thanks for the help! I've got things working locally doing it this way, but there seemed to be a few issues in `jupyter-sphinx` that stop it from working at first. 

Firstly, the `language` attribute is set on the wrong node in [execute.py](https://github.com/jupyter/jupyter-sphinx/blob/28468f22ae8fb9d444ee3b11af04542e7427cb3c/jupyter_sphinx/execute.py#L207), as it currently sets the `language` of the `CellInputNode`, rather than the child `literal-block` . This means this line isn't actually doing anything (which you can confirm by commenting out that logic or setting `lexer` to whatever you like - the resultant `div` in html output always has a class of `highlight-default`). Instead, it should be:
```
source = node.children[0].children[0]
```

Fixing this then causes syntax highlighting to break, as the line [here](https://github.com/jupyter/jupyter-sphinx/blob/28468f22ae8fb9d444ee3b11af04542e7427cb3c/jupyter_sphinx/__init__.py#L285) defines the wrong name - it should be `"ipython3"` (as per [the definition](https://github.com/ipython/ipython/blob/e4ce5023ac90dee412387c0e9c6a2bbdce0b0b3c/IPython/lib/lexers.py#L76) in the ipython package)

After fixing both of these the highlighting works as intended, and for example in the html output, normal jupyter-execute blocks now have a class of `highlight-ipython3` rather than the current `highlight-default`, and our custom highlighting works if I change the kernel. 

Hopefully this makes sense and I've understood what's going on. I can open a pull request if you want, but it's only a two line change. Thanks again for the help!

**Comment by akhmerov** [comment]
@philj56 thanks for following through! Your description sounds correct, and I'd really appreciate a PR with the fixes.

**Comment by philj56** [comment]
No problem, it's #181

**Comment by akhmerov** [comment]
@philj56 @SeanDS I think this issue may probably be closed now, is that right?

**Comment by SeanDS** [comment]
Looks like it! Thanks.

**Comment by akhmerov** [comment]
I would like to include a few more things in the 0.4 milestone (#165 seems pretty important, also #169 should be useful).
