### ISSUE TITLE
outdated docs

### ISSUE THREAD

**Issue by ManonMarchand** [jupyter/jupyter-sphinx#213]
Hi, 

I looks like your workflow `artifact.yml` to update the docs don't work cause the online version corresponds to the version 0.3.0 while the docs in this repo are way more complete now.

I don't know how to help though.

**Comment by CommonClimate** [comment]
agreed, docs are badly out of date.

**Comment by akhmerov** [comment]
The issue is with the readthedocs settings; I've triggered a rebuild, should be OK now.

@SylvainCorlay, I don't seem to have the permissions to configure a readthedocs webhook. I've added you as a maintainer on the rtd. Can you please enable the webhook at https://readthedocs.org/dashboard/jupyter-sphinx/integrations/ or bump my permissions for this repo?
