### ISSUE TITLE
Consider relation with IPython sphinxext

### ISSUE THREAD

**Issue by akhmerov** [jupyter/jupyter-sphinx#36]
Brought up by @Carreau.

IPython has an extension [similar in spirit](https://ipython.readthedocs.io/en/stable/sphinxext.html).

As far as I can tell, the key implementation difference is that it is implemented directly via IPython's `InteractiveShell` instead of `nbconvert` and `nbformat`.

Thinking further the practical consequences of this are that IPython's extension:

- is much more lightweight (fewer dependencies) and fast (guessing here)
- by definition only supports IPython code
- only supports text output, as opposed to arbitrary mimetypes/widgets/???

---

The possible courses of action are:

- Do nothing
- Clarify the relation between the two extensions in the documentation
- Deprecate and then remove the IPython's one
- Take this one over into IPython (would be weird though, because it'd make IPython depend on nbconvert/nbformat and probably a bunch of other stuff)

**Comment by akhmerov** [comment]
@Carreau what's your opinion here?

**Comment by Peque** [comment]
@akhmerov @Carreau Did you have the chance to discuss this internally? :blush: 

We were having a small discussion at https://github.com/pvlib/pvlib-python/issues/1379 and we wondered: as of today, would you recommend adopting Jupyter's directive instead of IPython's? Perhaps due to better support or development activity (and even if there is no plan to deprecate the IPython directive any time soon).

**Comment by akhmerov** [comment]
To the best of my knowledge your description is correct. The main advantage of jupyter-sphinx over the ipython directive is its ability to treat any jupyter-compatible outputs. You can also consider the executable books stack—that one is much more actively developed.

**Comment by 12rambau** [comment]
superceeded by https://github.com/jupyter/jupyter-sphinx/issues/64
