### ISSUE TITLE
explore how to improve styling

### ISSUE THREAD

**Issue by akhmerov** [jupyter/jupyter-sphinx#71]
We have two problems:

- Right now the inputs and outputs are not visibly different
- stderr isn't different from stdout

We should try to improve on both of these, but I think it's rather hard.

**Comment by danielballan** [comment]
I really like this library. Thank you for contributing this work to the Jupyter ecosystem!

As a longtime user of the IPython sphinx extension, it occurs to me that one way to make inputs and outputs visibly different is to display `In [...]` and `Out [...]` prompts to the left of the code blocks. Unlike the IPython sphinx extension, however, the prompts would apply to a whole code block at once, not to individual lines. (See [this page from the pandas documentation](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) for exampel of what prompts-per-line look like.) This makes the code examples more compact and also easier to copy/paste.

Do you think this is a suitable approach?

**Comment by akhmerov** [comment]
@danielballan thanks for the idea. It's an possible choice, but there are some subtleties to consider:

- jupyter distinguishes the *output* and the display data. Within the notebook/lab only output is labeled with `Out[...]`:
![image](https://user-images.githubusercontent.com/2069677/62621926-60c19400-b91d-11e9-97b7-d608e0d0989f.png)
- Documentation may reasonably hide some cells, for example boilerplate with imports. It will then be confusing to the readers why the first code they see is `In[3]`.
- The layout isn't obvious if we're displaying rich output. If we just show text, then the formatting is clear, but what kind of DOM should we produce if we have an image?
- What to do if the input or the output are hidden?

**Comment by pohlt** [comment]
I just recently realized that both the code fragments and their input are styled as code. While this is an obvious choice for the code fragments, it's kind of misleading for the output. When I do a `print("The world is nice")`, the "is" in the output is emphasized as a keyword. The output of pre-formatted text is also messed up (e.g. when printing a numpy array).

Again, I don't know the internals, so what I'm proposing might not be feasible, but how about styling the output as pre-formatted text (and optionally giving it a different background color and/or font). IIRC, pre-formatted texts are part of reStructuredText and Sphinx.

**Comment by akhmerov** [comment]
OK, highlighting is outright a bug; that we should fix. Styling should be within reach, however I don't know off the top of my head how to make it consistent across different formats (latex / html).

**Comment by akhmerov** [comment]
Done; the current master should have no output highlighting (which was there due to https://github.com/sphinx-doc/sphinx/issues/4679).

**Comment by pohlt** [comment]
Just tested it: works as advertised!
Let's see if it breaks things for others...

Thanks a lot, Anton! Looks much better now IMHO.

**Comment by seanpue** [comment]
I was wondering if maybe adding line numbering to the code would help to distinguish the code blocks. It's still a little hard to distinguish between code and output if nothing gets highlighted. There is a :linenos: directive in Sphinx code blocks, so I assume that might be possible. Perhaps there could be a global toggle so people could turn it on/off? Or it could be cell-level attribute.

**Comment by akhmerov** [comment]
I think this is issue is only partially addressed:

- stderr is now nicely different from the rest
- with line numbering there's also a difference between inputs and outputs, however line numbering is only a stopgap measure.

**Comment by seanpue** [comment]
I agree. I think adding a few more CSS styles  (with `classes=`) for the basic elements may be necessary so that the user can adjust it based on their theme, and so that it will work with the most common ones (Alabaster, RTD, any others?). These styles can loosely follow Jupyter's existing CSS model.

One option would be to set up a shadowed box around each container for the code/warnings/output/widgets. There is probably something in the default themes that would work, like the styling of an admonition. Then the output background could be transparent/white, and the code background grey. So it could be like the overall Jupyter interface, where the cells/outputs are in front of a background, but for jupyter-sphinx each cell/output would be separate. That container should probably only be present if the code is displayed, so if you are using jupyter-sphinx with hidden code to generate an image, widget, etc, it would not be in a visible container.

The other thing I would like to see adjusted is the vertical padding between the related code/warning/output/etc blocks so there is less space between them. If they are subsections of a container, that should be possible using CSS.

I can work on an example, if that sounds good. Generating it across themes would also be useful.

**Comment by pohlt** [comment]
+1
Dedicated CSS classes for all three types (input, stdout, stderr) is the way to go IMHO.


________________________________

**Comment by seanpue** [comment]
Here is a sample with #87 (css inserts) and current #83 (continuous line #s): 
    https://graphtransliterator.readthedocs.io/en/latest/usage.html
I think it looks pretty good! What do you think? Comments/tweaks are encouraged. Check out #87.
