### ISSUE TITLE
Conditional compilation?

### ISSUE THREAD

**Issue by grothesque** [jupyter/jupyter-sphinx#99]
We are facing the following problem: one of our jupyter-sphinx-powered RST-files takes a very long time to execute.  We would like to exclude it most of the time when the documentation is built and only include it for final builds.

Now sphinx offers an `ifconfig` directive for conditional execution, but this does not seem to help us here.  Even if we remove the slow file from `index.rst` it seems that jupyter-sphinx insists on executing it.  Are we missing anything here?

**Comment by akhmerov** [comment]
The compilation of files not included in the TOC likely happens because we inject the processing at the place where sphinx reads the sources, but before the tree construction. The fix for that would be to move jupyter-sphinx pass later down in the sphinx pipeline.

**Comment by akhmerov** [comment]
Upon further investigation, this behavior is intrinsic to sphinx: it will build all files that it finds, regardless of whether they are in a toctree or not. It's possible to exclude files by using `exclude_patterns = ['slow_to_execute.rst']` in sphinx configuration.

I don't think it would be consistent trying to override the sphinx behavior for the purpose of a single extension, but if you have a suggestion, please let me know.

Also if parts of the document are excluded from the toctree at the initial build, they won't be run anymore since as of #107, the execution happens at a post-transform stage and not at the reading stage.
